#!/usr/bin/env python
"""
Visualizes aggregate statistics for a collection of semantic journeys.

This script loads a journeys JSON file and the corresponding metrics CSV file
generated by 'analyze_semantic_shift.py'. It produces two high-level,
interactive visualizations for the entire dataset:

1.  A heatmap showing the distribution of where the maximum shift occurs across
    all texts, normalized by relative position. This reveals if a dataset
    favors "punchlines" (twists at the end) or other structures.
2.  A "spaghetti plot" overlaying the semantic journeys of the Top 50 texts
    with the highest max_shift scores, highlighting the #1 journey. This
    visualizes the "shape of surprise" for the most impactful texts.

Plots are saved as HTML files in 'data/outputs/analysis/semantic_shift/visualizations/'.

Usage:
    python 06_figures/visualize_aggregate_journeys.py <path_to_journeys.json> <path_to_metrics.csv> <dataset_name>

Example:
    python 06_figures/visualize_aggregate_journeys.py data/outputs/analysis/semantic_shift/journeys_shift_goodreads_popular_quote.json data/outputs/analysis/semantic_shift/semantic_shift_metrics.csv "Popular Quotes"
"""
import json
import argparse
import pandas as pd
import plotly.graph_objects as go
import sys
import os
import numpy as np

# Add project root to sys.path to allow absolute imports
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

import config

# --- Configuration ---
OUTPUT_DIR = config.BASE_OUTPUT_DIR / "semantic_shift" / "visualizations"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def plot_max_shift_position_heatmap(metrics_df, dataset_name):
    """
    Generates a heatmap of where the max shift occurs across all texts.
    """
    # Bin the relative positions into 10 bins (0-10%, 10-20%, etc.)
    bins = pd.cut(metrics_df['max_shift_relative_position'], bins=10, right=False, labels=[f"{i*10}-{(i+1)*10}%" for i in range(10)])
    binned_counts = bins.value_counts().sort_index()

    fig = go.Figure(go.Heatmap(
        z=[binned_counts.values],
        x=binned_counts.index,
        y=['Distribution'],
        colorscale='Viridis',
        hoverongaps=False,
        text=[f"{val}" for val in binned_counts.values],
        texttemplate="%{text}",
        showscale=False
    ))

    fig.update_layout(
        title=f"Where Does the 'Aha!' Moment Happen? (Distribution of Max Shift Position)<br><sup>Dataset: {dataset_name}</sup>",
        xaxis_title="Relative Position of Max Shift in Text",
        yaxis_title="",
        template='plotly_white'
    )
    return fig


def plot_top_50_spaghetti(journeys_data, metrics_df, dataset_name):
    """
    Generates a 'spaghetti plot' of the Top 50 highest-shift journeys.
    """
    top_50_indices = metrics_df.nlargest(50, 'max_shift')['original_index'].astype(str)
    
    fig = go.Figure()

    # Find the #1 journey to highlight
    top_1_index = top_50_indices.iloc[0]
    
    # Plot the other 49 journeys first with low opacity
    for idx in top_50_indices.iloc[1:]:
        journey = journeys_data.get(idx)
        if journey:
            shifts = [item[1] for item in journey]
            # Normalize token position to be 0-100%
            normalized_x = [(i / (len(shifts) - 1)) * 100 if len(shifts) > 1 else 0 for i in range(len(shifts))]
            fig.add_trace(go.Scatter(
                x=normalized_x, 
                y=shifts, 
                mode='lines', 
                line=dict(color='grey', width=1),
                opacity=0.5,
                hoverinfo='none'
            ))

    # Plot the #1 journey on top, highlighted
    top_journey = journeys_data.get(top_1_index)
    if top_journey:
        shifts = [item[1] for item in top_journey]
        normalized_x = [(i / (len(shifts) - 1)) * 100 if len(shifts) > 1 else 0 for i in range(len(shifts))]
        fig.add_trace(go.Scatter(
            x=normalized_x, 
            y=shifts, 
            mode='lines', 
            name='Highest Shift Journey',
            line=dict(color='crimson', width=4),
            text=f"Index: {top_1_index}",
            hoverinfo='text'
        ))

    fig.update_layout(
        title=f"The Shape of Surprise: Top 50 Semantic Journeys<br><sup>Dataset: {dataset_name}</sup>",
        xaxis_title="Relative Position in Text (%)",
        yaxis_title="Semantic Shift Score",
        template='plotly_white',
        showlegend=True
    )
    return fig


def create_metrics_from_journeys(journeys_data):
    """
    Calculates metrics directly from the journey data if a CSV is not available.
    """
    print("Metrics CSV not provided. Calculating metrics from journey data...")
    metrics = []
    for idx, journey in journeys_data.items():
        if not journey:
            continue
        
        tokens = [item[0] for item in journey]
        shifts = [item[1] for item in journey]
        
        if len(shifts) < 2:
            max_shift_value = 0
            max_shift_relative_position = np.nan
        else:
            # Ignore the first shift (always 0) for calculation
            shifts_arr = np.array(shifts[1:])
            max_shift_value = np.max(shifts_arr)
            max_shift_idx = np.argmax(shifts_arr)
            # The token causing the shift is at `max_shift_idx + 1` in the original token list
            max_shift_token_index = max_shift_idx + 1
            max_shift_relative_position = (max_shift_token_index / len(tokens)) * 100 if len(tokens) > 0 else 0

        metrics.append({
            'original_index': idx,
            'max_shift': max_shift_value,
            'max_shift_relative_position': max_shift_relative_position
        })
    
    df = pd.DataFrame(metrics)
    print(f"Calculated metrics for {len(df)} texts.")
    return df


def main():
    """Main function to load data and generate aggregate plots."""
    parser = argparse.ArgumentParser(description="Visualize aggregate metrics for a collection of semantic journeys.")
    parser.add_argument("journeys_json_path", type=str, help="Path to the input journeys JSON file.")
    parser.add_argument("dataset_name", type=str, help="A descriptive name for the dataset (e.g., 'Popular Quotes').")
    parser.add_argument("--metrics_csv_path", type=str, default=None, help="[Optional] Path to the semantic_shift_metrics.csv file.")
    args = parser.parse_args()

    # Load journey data
    try:
        with open(args.journeys_json_path, 'r', encoding='utf-8') as f:
            all_journeys = json.load(f)
    except FileNotFoundError:
        print(f"ERROR: Journeys file not found at {args.journeys_json_path}", file=sys.stderr)
        sys.exit(1)

    # Load metrics data or create it from journeys
    if args.metrics_csv_path:
        try:
            all_metrics_df = pd.read_csv(args.metrics_csv_path)
            # Filter for metrics relevant to the loaded journeys
            journey_indices = list(all_journeys.keys())
            all_metrics_df = all_metrics_df[all_metrics_df['original_index'].astype(str).isin(journey_indices)]
        except FileNotFoundError:
            print(f"Warning: Metrics CSV file not found at {args.metrics_csv_path}. Will calculate metrics from journey data instead.")
            all_metrics_df = create_metrics_from_journeys(all_journeys)
    else:
        all_metrics_df = create_metrics_from_journeys(all_journeys)
        
    print(f"Loaded {len(all_journeys)} journeys and using {len(all_metrics_df)} metrics. Generating aggregate visualizations for '{args.dataset_name}'...")

    # --- Generate and save heatmap ---
    fig_heatmap = plot_max_shift_position_heatmap(all_metrics_df, args.dataset_name)
    output_path_heatmap = OUTPUT_DIR / f"aggregate_heatmap_{args.dataset_name.replace(' ', '_').lower()}.html"
    fig_heatmap.write_html(output_path_heatmap)
    print(f"Saved max shift position heatmap to: {output_path_heatmap}")
    
    # --- Generate and save spaghetti plot ---
    fig_spaghetti = plot_top_50_spaghetti(all_journeys, all_metrics_df, args.dataset_name)
    output_path_spaghetti = OUTPUT_DIR / f"aggregate_spaghetti_{args.dataset_name.replace(' ', '_').lower()}.html"
    fig_spaghetti.write_html(output_path_spaghetti)
    print(f"Saved top 50 journeys spaghetti plot to: {output_path_spaghetti}")

if __name__ == "__main__":
    main() 