#!/usr/bin/env python
"""
Compares performance metrics between static (GloVe) and dynamic (SBERT) embeddings.

This script automates the comparison of analysis reports generated by
`analyze_static_embeddings.py` and `analyze_dynamic_embeddings.py`.

It finds corresponding report files in the static and dynamic output
directories, parses them to extract key performance metrics (including confidence
intervals and effect sizes), and presents them in a side-by-side summary table
and a set of publication-quality bar charts.

To run, simply execute from the terminal:
    python 05_analysis/compare_static_vs_dynamic_embeddings.py
"""

from __future__ import annotations

import pathlib
import re
from typing import Dict, List, Tuple

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import sys


def parse_report_metrics(report_path: pathlib.Path) -> Dict[str, float]:
    """
    Parses a text report file to extract key performance metrics.

    Args:
        report_path: The path to the analysis report file.

    Returns:
        A dictionary containing the metric names and their float values.
        Returns an empty dictionary if the file is not found.
    """
    if not report_path.exists():
        print(f"WARNING: Report file not found, skipping: {report_path}", file=sys.stderr)
        return {}

    text = report_path.read_text()
    metrics = {}

    # --- Regex patterns for metrics, now including confidence intervals ---
    # Pattern for metrics with confidence intervals, e.g., "Accuracy: 0.123 (95% CI: [0.111, 0.222])"
    ci_patterns = {
        "Accuracy": r"Overall Accuracy:\s+([0-9.]+)\s+\(95% CI: \[([0-9.]+),\s*([0-9.]+)\]\)",
        "AUC": r"ROC AUC Score:\s+([0-9.]+)\s+\(95% CI: \[([0-9.]+),\s*([0-9.]+)\]\)",
    }

    # Pattern for single-value metrics
    single_val_patterns = {
        "Silhouette": r"Mean Silhouette Score:\s+([0-9.]+)",
        # This will find all effect sizes and we will average them later
        "Cliff's Delta": r"Cliff's Delta \(Effect Size\):\s+([0-9.-]+)",
    }

    for name, pattern in ci_patterns.items():
        match = re.search(pattern, text)
        if match:
            metrics[name] = float(match.group(1))
            metrics[f"{name}_CI_low"] = float(match.group(2))
            metrics[f"{name}_CI_high"] = float(match.group(3))

    for name, pattern in single_val_patterns.items():
        matches = re.findall(pattern, text)
        if matches:
            # For metrics that might appear multiple times (like RBC), average them.
            mean_value = np.mean([float(val) for val in matches])
            metrics[name] = mean_value

    return metrics


def create_comparison_plots(df: pd.DataFrame, output_dir: pathlib.Path):
    """
    Generates and saves bar plots comparing Static and Dynamic model performance.
    """
    print("\n--- Generating Comparison Plots ---")
    sns.set_style("white")  # Use a clean style with no grid

    # Define a professional color palette
    model_palette = {"Static (GloVe)": "#6B7280", "Dynamic (SBERT)": "#1F77B4"}

    metrics_to_plot = {
        "Accuracy": "Accuracy Score",
        "AUC": "Area Under Curve (AUC)",
        "Cliff's Delta": "Mean Effect Size (Cliff's Delta)",
        "Silhouette": "Mean Silhouette Score",
    }

    for metric_key, plot_title in metrics_to_plot.items():
        if metric_key not in df["Metric"].values:
            continue

        # Use .copy() to avoid SettingWithCopyWarning
        metric_df = df[df["Metric"] == metric_key].copy()

        # Clean up long analysis names for better readability on the x-axis
        metric_df["Analysis"] = (
            metric_df["Analysis"]
            .str.replace("Glove ", "")
            .str.replace(" Vs. ", " vs. ")
            .str.replace("T50", "T50") # Consolidate spacing
        )

        plt.figure(figsize=(12, 7))

        # Melt the DataFrame to have 'Model' and 'Score' columns for seaborn
        plot_data = metric_df.melt(
            id_vars=["Analysis"],
            value_vars=["Static (GloVe)", "Dynamic (SBERT)"],
            var_name="Model",
            value_name="Score"
        )

        ax = sns.barplot(
            x="Analysis", y="Score", hue="Model", data=plot_data, palette=model_palette
        )

        # --- Add error bars if confidence intervals are available ---
        if f"{metric_key}_CI_low" in metric_df.columns:
            # Calculate asymmetric errors
            errors_low_static = metric_df["Static (GloVe)"] - metric_df[f"{metric_key}_CI_low_static"]
            errors_high_static = metric_df[f"{metric_key}_CI_high_static"] - metric_df["Static (GloVe)"]
            static_errors = [errors_low_static.values, errors_high_static.values]

            errors_low_dynamic = metric_df["Dynamic (SBERT)"] - metric_df[f"{metric_key}_CI_low_dynamic"]
            errors_high_dynamic = metric_df[f"{metric_key}_CI_high_dynamic"] - metric_df["Dynamic (SBERT)"]
            dynamic_errors = [errors_low_dynamic.values, errors_high_dynamic.values]

            # The number of locations for bars is len(analyses)
            x_coords = np.arange(len(metric_df["Analysis"].unique()))

            # Add error bars to the barplot
            # We need to manually add them to the correct bar locations
            ax.errorbar(x=x_coords - 0.2, y=metric_df["Static (GloVe)"], yerr=static_errors, fmt='none', c='black', capsize=3, alpha=0.6)
            ax.errorbar(x=x_coords + 0.2, y=metric_df["Dynamic (SBERT)"], yerr=dynamic_errors, fmt='none', c='black', capsize=3, alpha=0.6)


        plt.title(f"Comparison of {plot_title}", fontsize=18, pad=20)
        plt.ylabel(plot_title, fontsize=14)
        plt.xlabel("Analysis", fontsize=14)
        plt.xticks(rotation=25, ha="right", fontsize=12)
        plt.yticks(fontsize=12)
        plt.legend(title=None, loc="best", fontsize=12)
        sns.despine() # Remove top and right spines
        plt.tight_layout()

        # Save the plot
        plot_path = output_dir / f"comparison_{metric_key.lower().replace(' ', '_').replace('(', '').replace(')', '')}.png"
        plt.savefig(plot_path, dpi=300, bbox_inches='tight')
        print(f"Saved plot to {plot_path}")
        plt.close()


def main():
    """
    Main function to find, parse, and compare analysis reports.
    """
    # --- Define Input and Output Directories ---
    static_dir = pathlib.Path("data/outputs/analysis/static")
    dynamic_dir = pathlib.Path("data/outputs/analysis/dynamic")
    comparison_dir = pathlib.Path("data/outputs/analysis/comparison")

    # --- Create Output Directory ---
    comparison_dir.mkdir(parents=True, exist_ok=True)

    if not static_dir.exists() or not dynamic_dir.exists():
        print(
            "ERROR: Both 'data/outputs/analysis/static' and 'data/outputs/analysis/dynamic' "
            "directories must exist and contain report files."
        )
        return

    # Find all static analysis reports to use as the baseline
    static_reports = sorted(static_dir.glob("comprehensive_analysis*.txt"))

    if not static_reports:
        print(f"No analysis reports found in {static_dir}.")
        return

    comparison_data: List[Dict] = []

    # --- Iterate through reports and find matching pairs ---
    for static_path in static_reports:
        # Construct the expected dynamic report path by removing 'glove-' prefixes
        # This assumes a consistent naming convention between static and dynamic reports
        dynamic_filename = static_path.name.replace("glove-", "")
        dynamic_path = dynamic_dir / dynamic_filename

        # Parse both reports
        static_metrics = parse_report_metrics(static_path)
        dynamic_metrics = parse_report_metrics(dynamic_path)
        
        if not static_metrics or not dynamic_metrics:
            print(f"Could not find or parse a matching report for {static_path.name}. Skipping.")
            continue

        # Generate a clean name for the analysis being compared
        analysis_name = (
            static_path.stem.replace("comprehensive_analysis_", "")
            .replace("glove_", "")
            .replace("_vs_", " vs. ")
            .replace("_", " ")
            .replace("-", " ")
            .title()
        )

        all_metric_keys = sorted(
            list(
                {k.split('_CI_')[0] for k in static_metrics.keys()} |
                {k.split('_CI_')[0] for k in dynamic_metrics.keys()}
            )
        )

        for metric in all_metric_keys:
            row = {"Analysis": analysis_name, "Metric": metric}
            
            # --- Static Metrics ---
            row["Static (GloVe)"] = static_metrics.get(metric)
            if f"{metric}_CI_low" in static_metrics:
                row[f"{metric}_CI_low_static"] = static_metrics[f"{metric}_CI_low"]
                row[f"{metric}_CI_high_static"] = static_metrics[f"{metric}_CI_high"]

            # --- Dynamic Metrics ---
            row["Dynamic (SBERT)"] = dynamic_metrics.get(metric)
            if f"{metric}_CI_low" in dynamic_metrics:
                row[f"{metric}_CI_low_dynamic"] = dynamic_metrics[f"{metric}_CI_low"]
                row[f"{metric}_CI_high_dynamic"] = dynamic_metrics[f"{metric}_CI_high"]
                
            comparison_data.append(row)

    if not comparison_data:
        print("Could not find any matching reports to compare.")
        return

    # --- Create and display the summary table ---
    df = pd.DataFrame(comparison_data)

    # Calculate difference
    df["Difference"] = df["Dynamic (SBERT)"] - df["Static (GloVe)"]

    # --- Format table for display ---
    display_df = df.copy()

    # Format CI strings for display
    for metric in ["Accuracy", "AUC"]:
        if metric in display_df["Metric"].values:
            # Format Static
            static_mask = display_df["Metric"] == metric
            display_df.loc[static_mask, "Static (GloVe)"] = display_df[static_mask].apply(
                lambda r: f"{r['Static (GloVe)']:.3f} ({r[f'{metric}_CI_low_static']:.3f}-{r[f'{metric}_CI_high_static']:.3f})"
                if pd.notna(r[f'{metric}_CI_low_static']) else f"{r['Static (GloVe)']:.3f}",
                axis=1
            )
            # Format Dynamic
            display_df.loc[static_mask, "Dynamic (SBERT)"] = display_df[static_mask].apply(
                lambda r: f"{r['Dynamic (SBERT)']:.3f} ({r[f'{metric}_CI_low_dynamic']:.3f}-{r[f'{metric}_CI_high_dynamic']:.3f})"
                if pd.notna(r[f'{metric}_CI_low_dynamic']) else f"{r['Dynamic (SBERT)']:.3f}",
                axis=1
            )

    # Select and reorder columns for the final display
    display_cols = ["Analysis", "Metric", "Static (GloVe)", "Dynamic (SBERT)", "Difference"]
    display_df = display_df[display_cols].set_index(["Analysis", "Metric"])

    print("\n--- Performance Comparison: Static (GloVe) vs. Dynamic (SBERT) ---")
    print("\nThis table compares key metrics between the two embedding strategies.")
    print("Confidence intervals (95% CI) are shown in parentheses where applicable.")
    print("A positive 'Difference' indicates that Dynamic (SBERT) performed better.\n")

    pd.set_option('display.max_columns', None)
    pd.set_option('display.width', 140)
    
    # Use a lambda for the float format to avoid the TypeError
    pd.set_option('display.float_format', '{:.3f}'.format)
    
    print(display_df.to_string())

    # Save the detailed comparison to a file in the new directory
    output_path = comparison_dir / "performance_comparison_detailed.csv"
    df.to_csv(output_path, index=False, float_format="%.4f")
    print(f"\nDetailed comparison summary saved to {output_path}")

    # --- Generate and save plots to the new directory ---
    create_comparison_plots(df, comparison_dir)


if __name__ == "__main__":
    main() 