#!/usr/bin/env python
"""
Analyzes the topic coherence scores generated by perform_topic_modeling.py.

This script loads the summary of the topic modeling results, calculates
descriptive statistics for the topic coherence scores, and generates a
publication-quality visualization of the coherence for each topic.

This provides a quantitative and objective evaluation of the topic model's quality.

Usage:
    python 05_analysis/analyze_topic_coherence.py
"""
from __future__ import annotations

import pathlib
import pandas as pd
import plotly.express as px


def main():
    """Main function to load, analyze, and visualize topic coherence."""
    
    # --- Parameters ---
    input_csv_path = pathlib.Path("data/outputs/analysis/topic_modeling/topics_summary.csv")
    output_dir = pathlib.Path("data/outputs/analysis/topic_modeling")
    output_plot_path = output_dir / "topic_coherence_scores.png"

    # --- Load Data ---
    print(f"--- Loading topic summary from: {input_csv_path} ---")
    try:
        df = pd.read_csv(input_csv_path)
    except FileNotFoundError:
        print(f"ERROR: Could not find the topic summary file at {input_csv_path}.")
        print("Please run `perform_topic_modeling.py` first.")
        return

    # --- Analyze Coherence Scores ---
    print("\n--- Analyzing Topic Coherence ---")
    
    # Filter out the outlier topic (-1), which does not have a coherence score
    df_topics = df[df["Topic"] != -1].copy()
    
    # Ensure coherence is numeric and drop any topics where it couldn't be calculated
    df_topics["Coherence"] = pd.to_numeric(df_topics["Coherence"], errors="coerce")
    df_topics.dropna(subset=["Coherence"], inplace=True)
    
    # Descriptive Statistics
    mean_coherence = df_topics["Coherence"].mean()
    median_coherence = df_topics["Coherence"].median()
    std_coherence = df_topics["Coherence"].std()
    min_coherence = df_topics["Coherence"].min()
    max_coherence = df_topics["Coherence"].max()

    print("\n--- Coherence Score Statistics ---")
    print(f"Mean Coherence (c_v):   {mean_coherence:.4f}")
    print(f"Median Coherence (c_v): {median_coherence:.4f}")
    print(f"Std. Dev.:              {std_coherence:.4f}")
    print(f"Min Coherence:          {min_coherence:.4f}")
    print(f"Max Coherence:          {max_coherence:.4f}")

    # Top 5 Most Coherent Topics
    df_sorted = df_topics.sort_values(by="Coherence", ascending=False)
    print("\n--- Top 5 Most Coherent Topics ---")
    print(df_sorted.head(5)[["Topic", "Name", "Coherence", "Count"]])

    # Bottom 5 Least Coherent Topics
    print("\n--- Bottom 5 Least Coherent Topics ---")
    print(df_sorted.tail(5)[["Topic", "Name", "Coherence", "Count"]])
    
    # --- Visualize Coherence Scores ---
    print(f"\n--- Generating Coherence Visualization ---")
    
    # For visualization, create a more readable topic label
    df_sorted['TopicLabel'] = df_sorted['Name'].apply(lambda x: x.replace('_', ' '))

    fig = px.bar(
        df_sorted,
        x="Coherence",
        y="TopicLabel",
        orientation='h',
        title="Topic Coherence Scores (c_v)",
        labels={"TopicLabel": "Topic Keywords", "Coherence": "Coherence Score (NPMI)"},
        height=1600,
        width=1000,
    )

    fig.update_layout(
        yaxis={'categoryorder':'total ascending'},
        xaxis_title="Coherence Score (c_v)",
        yaxis_title="Topic Keywords",
        font=dict(family="Arial", size=12),
        title_font_size=20,
        plot_bgcolor='white',
    )
    
    fig.update_yaxes(tickfont=dict(size=10))

    fig.write_image(str(output_plot_path), scale=2)
    print(f"Saved coherence score plot to {output_plot_path}")


if __name__ == "__main__":
    main() 